apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-grpc-1
  description: spring-boot-grpc-1
  annotations:
    github.com/project-slug: shmidt-i-test/spring-boot-grpc-1
    backstage.io/techdocs-ref: github:https://github.com/shmidt-i-test/spring-boot-grpc-1
spec:
  type: service
  lifecycle: experimental
  owner: shmidt-i
